/* Cal.com embed for the "Book Call Strategi 15 Minit" CTAs.

   The CTAs are plain links to cal.com carrying Cal's embed attributes
   (data-cal-link, data-cal-namespace, data-cal-config), so they work without
   this file — it upgrades them to the in-page popup the design asks for. Cal's
   embed.js finds and wires them itself once the namespace below is registered.

   Not generated by the design export; maintained here. */
(function () {
  if (window.__calEmbed) return;
  window.__calEmbed = true;

  /* Cal.com's own loader snippet, verbatim. */
  (function (C, A, L) {
    var p = function (a, ar) { a.q.push(ar); };
    var d = C.document;
    C.Cal = C.Cal || function () {
      var cal = C.Cal, ar = arguments;
      if (!cal.loaded) {
        cal.ns = {};
        cal.q = cal.q || [];
        d.head.appendChild(d.createElement('script')).src = A;
        cal.loaded = true;
      }
      if (ar[0] === L) {
        var api = function () { p(api, arguments); };
        var namespace = ar[1];
        api.q = api.q || [];
        if (typeof namespace === 'string') {
          cal.ns[namespace] = cal.ns[namespace] || api;
          p(cal.ns[namespace], ar);
          p(cal, ['initNamespace', namespace]);
        } else {
          p(cal, ar);
        }
        return;
      }
      p(cal, ar);
    };
  })(window, 'https://app.cal.com/embed/embed.js', 'init');

  /* The one event the CTAs point at. Keep in step with their data-cal-config. */
  Cal('init', 'strategy-meeting', { origin: 'https://app.cal.com' });
  Cal.ns['strategy-meeting']('ui', {
    hideEventTypeDetails: false,
    layout: 'month_view'
  });
})();
